// Demo data for Skill Bridge (Sprint 1)
var SKILLBRIDGE_DATA = {
  workers: [
    { id: 1, name: 'Ali Khan', service: 'Plumber', experience: 5, rating: 4.7, bio: 'Experienced in residential plumbing.', availability: ['Today','Tomorrow'], photo: 'images/hasnain.jpeg', verified: true, price: 25, location: 'Lahore' },
    { id: 2, name: 'Rashid Khan', service: 'Plumber', experience: 6, rating: 4.8, bio: 'Specialist in leak repairs and pipe fitting.', availability: ['Weekend'], photo: 'images/hassan.jpeg', verified: true, price: 30, location: 'Islamabad' },
    { id: 3, name: 'Ahmed Ali', service: 'Plumber', experience: 4, rating: 4.5, bio: 'Emergency plumbing services.', availability: ['Today','Tomorrow','Weekend'], photo: 'images/maan.jpeg', verified: false, price: 20, location: 'Rawalpindi' },
    { id: 4, name: 'Fatima Noor', service: 'Plumber', experience: 7, rating: 4.9, bio: 'Renovation and installation expert.', availability: ['Tomorrow'], photo: 'images/ayesha.jpeg', verified: true, price: 40, location: 'Lahore' },
    { id: 5, name: 'Bilal Hussain', service: 'Plumber', experience: 3, rating: 4.3, bio: 'Affordable and quick fixes.', availability: ['Weekend'], photo: 'images/sohaib.jpeg', verified: false, price: 15, location: 'Islamabad' },
    { id: 6, name: 'Noor Malik', service: 'Plumber', experience: 8, rating: 4.9, bio: 'Commercial plumbing and maintenance.', availability: ['Today','Weekend'], photo: 'images/ayza.jpeg', verified: true, price: 45, location: 'Karachi' },
    { id: 7, name: 'Zain Khan', service: 'Plumber', experience: 5, rating: 4.6, bio: 'Bathroom and kitchen plumbing.', availability: ['Tomorrow','Weekend'], photo: 'images/talal.jpeg', verified: true, price: 25, location: 'Lahore' },
    { id: 8, name: 'Maria Ali', service: 'Plumber', experience: 2, rating: 4.2, bio: 'Small jobs and maintenance.', availability: ['Today'], photo: 'images/eshaal.jpeg', verified: false, price: 12, location: 'Rawalpindi' },
    { id: 9, name: 'Sara Ahmed', service: 'Electrician', experience: 7, rating: 4.9, bio: 'Licensed electrician, fast troubleshooting.', availability: ['Today','Weekend'], photo: 'images/fizza.jpeg', verified: true, price: 35, location: 'Islamabad' },
    { id: 10, name: 'Tariq Jamil', service: 'Electrician', experience: 12, rating: 4.8, bio: 'Expert in residential wiring and smart home setups.', availability: ['Tomorrow'], photo: 'images/hasnain.jpeg', verified: true, price: 50, location: 'Lahore' },
    { id: 11, name: 'Omar Farooq', service: 'Electrician', experience: 5, rating: 4.6, bio: 'Commercial electrical installations.', availability: ['Weekend'], photo: 'images/hassan.jpeg', verified: true, price: 30, location: 'Karachi' },
    { id: 12, name: 'Usman Ali', service: 'Electrician', experience: 8, rating: 4.7, bio: 'Panel upgrades and lighting.', availability: ['Today','Tomorrow'], photo: 'images/maan.jpeg', verified: true, price: 40, location: 'Rawalpindi' },
    { id: 13, name: 'Ayesha Khan', service: 'Electrician', experience: 4, rating: 4.5, bio: 'Appliance repair and minor electrical fixes.', availability: ['Weekend'], photo: 'images/ayesha.jpeg', verified: false, price: 20, location: 'Islamabad' },
    { id: 14, name: 'Hassan Raza', service: 'Electrician', experience: 10, rating: 4.9, bio: 'Heavy-duty wiring and generator setups.', availability: ['Today','Tomorrow','Weekend'], photo: 'images/sohaib.jpeg', verified: true, price: 60, location: 'Lahore' },
    { id: 15, name: 'Kashif Mehmood', service: 'Electrician', experience: 6, rating: 4.4, bio: 'Affordable electrical services.', availability: ['Tomorrow'], photo: 'images/talal.jpeg', verified: false, price: 22, location: 'Karachi' },
    { id: 16, name: 'Noman Tariq', service: 'Electrician', experience: 9, rating: 4.8, bio: 'Specialist in outdoor and security lighting.', availability: ['Weekend'], photo: 'images/sumer.jpeg', verified: true, price: 45, location: 'Rawalpindi' },
    { id: 17, name: 'Zahra Batool', service: 'Electrician', experience: 3, rating: 4.3, bio: 'Quick troubleshooting and repairs.', availability: ['Today'], photo: 'images/summaya.jpeg', verified: false, price: 18, location: 'Islamabad' },

    { id: 18, name: 'John Doe', service: 'Carpenter', experience: 4, rating: 4.4, bio: 'Custom furniture and repairs.', availability: ['Tomorrow','Weekend'], photo: 'images/hasnain.jpeg', verified: true, price: 25, location: 'Lahore' },
    { id: 19, name: 'Wasim Akram', service: 'Carpenter', experience: 15, rating: 4.9, bio: 'Master carpenter with expertise in wooden structures.', availability: ['Today','Tomorrow'], photo: 'images/hassan.jpeg', verified: true, price: 55, location: 'Karachi' },
    { id: 20, name: 'Arsalan Baig', service: 'Carpenter', experience: 6, rating: 4.6, bio: 'Cabinet making and remodeling.', availability: ['Weekend'], photo: 'images/maan.jpeg', verified: true, price: 30, location: 'Islamabad' },
    { id: 21, name: 'Kamran Akmal', service: 'Carpenter', experience: 8, rating: 4.7, bio: 'Expert in door and window framing.', availability: ['Today'], photo: 'images/talal.jpeg', verified: true, price: 35, location: 'Rawalpindi' },
    { id: 22, name: 'Sana Javed', service: 'Carpenter', experience: 5, rating: 4.5, bio: 'Wood polishing and restoration.', availability: ['Tomorrow','Weekend'], photo: 'images/ayesha.jpeg', verified: false, price: 20, location: 'Lahore' },
    { id: 23, name: 'Rizwan Ahmed', service: 'Carpenter', experience: 11, rating: 4.8, bio: 'Custom woodwork for luxury homes.', availability: ['Today','Tomorrow','Weekend'], photo: 'images/sohaib.jpeg', verified: true, price: 65, location: 'Islamabad' },
    { id: 24, name: 'Farhan Saeed', service: 'Carpenter', experience: 7, rating: 4.6, bio: 'General carpentry and repairs.', availability: ['Weekend'], photo: 'images/sumer.jpeg', verified: true, price: 28, location: 'Karachi' },
    { id: 25, name: 'Ali Zafar', service: 'Carpenter', experience: 9, rating: 4.8, bio: 'Specialist in built-in wardrobes.', availability: ['Today','Tomorrow'], photo: 'images/hasnain.jpeg', verified: true, price: 45, location: 'Lahore' },
    { id: 26, name: 'Bilal Saeed', service: 'Carpenter', experience: 4, rating: 4.2, bio: 'Affordable furniture fixes.', availability: ['Tomorrow'], photo: 'images/talal.jpeg', verified: false, price: 15, location: 'Rawalpindi' },

    { id: 27, name: 'Ravi Kumar', service: 'Mechanic', experience: 6, rating: 4.8, bio: 'Vehicle diagnostics and repairs.', availability: ['Today','Tomorrow'], photo: 'images/maan.jpeg', verified: true, price: 40, location: 'Islamabad' },
    { id: 28, name: 'Adnan Sami', service: 'Mechanic', experience: 12, rating: 4.9, bio: 'Expert in German cars.', availability: ['Tomorrow','Weekend'], photo: 'images/hasnain.jpeg', verified: true, price: 70, location: 'Lahore' },
    { id: 29, name: 'Imran Hashmi', service: 'Mechanic', experience: 8, rating: 4.7, bio: 'Engine overhauls and tuning.', availability: ['Today','Weekend'], photo: 'images/hassan.jpeg', verified: true, price: 50, location: 'Karachi' },
    { id: 30, name: 'Salman Khan', service: 'Mechanic', experience: 5, rating: 4.6, bio: 'Brake and suspension specialist.', availability: ['Tomorrow'], photo: 'images/sohaib.jpeg', verified: true, price: 35, location: 'Rawalpindi' },
    { id: 31, name: 'Shahrukh Khan', service: 'Mechanic', experience: 14, rating: 4.9, bio: 'Master mechanic for all vehicles.', availability: ['Today','Tomorrow','Weekend'], photo: 'images/talal.jpeg', verified: true, price: 80, location: 'Lahore' },
    { id: 32, name: 'Aamir Khan', service: 'Mechanic', experience: 7, rating: 4.7, bio: 'AC and electrical systems repair.', availability: ['Weekend'], photo: 'images/sumer.jpeg', verified: false, price: 45, location: 'Islamabad' },
    { id: 33, name: 'Saif Ali', service: 'Mechanic', experience: 9, rating: 4.8, bio: 'Transmission and clutch expert.', availability: ['Today','Tomorrow'], photo: 'images/maan.jpeg', verified: true, price: 55, location: 'Karachi' },
    { id: 34, name: 'Hrithik Roshan', service: 'Mechanic', experience: 4, rating: 4.5, bio: 'Quick lube and oil changes.', availability: ['Tomorrow'], photo: 'images/hassan.jpeg', verified: false, price: 25, location: 'Lahore' },
    { id: 35, name: 'Ranbir Kapoor', service: 'Mechanic', experience: 6, rating: 4.6, bio: 'General car maintenance.', availability: ['Today','Weekend'], photo: 'images/hasnain.jpeg', verified: true, price: 30, location: 'Rawalpindi' }
  ]
};
